# Generated by Django 4.0.3 on 2022-03-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ht', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature_humidity',
            name='create_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='創建日期'),
        ),
    ]
