# Generated by Django 4.0.3 on 2022-03-16 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temperature_humidity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature', models.CharField(blank=True, max_length=50, verbose_name='溫度')),
                ('humidity', models.CharField(blank=True, max_length=50, verbose_name='濕度')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='創建日期')),
            ],
            options={
                'verbose_name': '溫度濕度',
                'verbose_name_plural': '溫度濕度',
                'ordering': ('id',),
            },
        ),
    ]
